Dev 519 resumption tokens after first page
hathitrust/oai_solr pull request #15
Opened 2022-12-05 20:08 UTC by billdueber

The `OAI::Provider::ResumptionToken` created from a partial
result was being set, somehow, as just the solr string (I believe it's because it was missing the namespace). This
code builds the new token from the dregs of the
old one (if it exists) to make sure the :prefix (namespace),
:from, and :until match with what had been sent previously.

2022-12-05 20:24 UTC, aelkiss commented on lib/oai_solr/partial_result.rb
> +        {prefix: "oai_dc"}
Also isn't this already what `https://github.com/hathitrust/oai_solr/blob/4ec4b55bb1ce35aa596489ee2ad35c59180a1498/lib/oai_solr/model.rb#L53` is (clunkily) doing? I think there is some opportunity to clean up `OAISolr::Model` and reduce the duplication..

2022-12-05 20:46 UTC, billdueber commented on lib/oai_solr/partial_result.rb
> +        {prefix: "oai_dc"}
You're right, of course, on both counts. I'll figure out a decent way abstract it out.

2022-12-07 18:07 UTC, aelkiss commented
Looks pretty good to me. I will deploy in testing and make sure it's working as expected.

2022-12-07 18:42 UTC, aelkiss requested changes
`nextCursorMark` doesn't seem to be updating; not sure if that's because it isn't making it to solr or the next cursor mark isn't being put correctly in the output token. Should be easy enough to test that we get a different resumption token back than the one we fed in.

2022-12-07 18:42 UTC, aelkiss commented on lib/oai_solr/partial_result.rb
> +      opts = @opts.merge(last: @response["nextCursorMark"])
Something doesn't quite seem to be working as expected here. If I visit (for example) https://testing.oai.kubernetes.hathitrust.org/oai?verb=ListRecords&resumptionToken=marc21.f(1970-01-01T00:00:00Z).u(2022-12-07T18:39:56Z):AoEpMDAwMDAwNjA5 

then I get exactly the same `resumptionToken` back and never progress beyond that page.

2022-12-07 18:54 UTC, billdueber commented on lib/oai_solr/partial_result.rb
> +      opts = @opts.merge(last: @response["nextCursorMark"])
I'll track it down. I was working too late to get the details right, apparently. Test will be easy to add.

2022-12-07 20:19 UTC, aelkiss approved these changes
Looking good to me now on testing.oai.hathitrust.org (first 20 pages of results, anyway).

Please go ahead and merge when ready.

2022-12-08 21:40 UTC, merged