Adding new class to convert marc to Dublin Core crosswalk
hathitrust/oai_solr pull request #26
Opened 2023-03-14 02:51 UTC by billdueber

[Work in progress. Got carried away and built a little extractor library. Still needs tests and to incorporate into `dublin_core.rb`]

This mostly follows the definition laid out by the Library of Congress at https://www.loc.gov/marc/marc2dc.html

Use is:

```
require "oai_solr/dublin_core_crosswalk"

dcc = OAISolr:DublinCoreCrosswalk.new

hash_of_element_value_pairs = dcc.full_map(record)

title = dcc.title(rec)
identifier = dcc.identifier(rec)

This will replace some of what's in `dublin_core.rb` and should eliminate
any calls to `MARC::Record.to_dublin_core`

2023-03-22 14:21 UTC, aelkiss reviewed
This all generally makes sense and looks good to me. There are a few places I have questions about why things were done a particular way & what the long-term plans are, but nothing that needs to block merging.

2023-03-22 14:21 UTC, aelkiss commented on lib/oai_solr/basic_marc_single_extractor.rb
> +      define_singleton_method(:matches_tag?, tag_matcher(@tags))
Here I understand why `define_singleton_method`, since the behavior of the method varies based on the provided tags & values. That said, I do wonder a little bit if the indirection of the lambdas is worth the performance benefit - i.e. we could more straightforwardly define `matches_tag?` as something like:

```
    def matches_tag?(tag)
      case @tags
      when Integer, String
        tag.to_s == @tags
      when Array
        @tags.map(&:to_s).uniq.include?(tag)
      when Range
        @tags.cover?(tag)
      else
        raise "Illegal argumrnt '#{tags_to_match.inspect}'"
      end
    end
```

It would offend my sensibilities too to do these operations over and over again, but I wonder if there's any premature optimization here (e.g. if the interpreter might optimize some of this away anyway)

Alternatively, I wonder if we should be doing something like defining a `MARCTagMatcher` class with subclasses for `MARCTagMatcher::Array`, `MARCTagMatcher::Range`, etc.. In any case, something to think about.

2023-03-22 16:01 UTC, moseshll requested changes
I'd like to see some tests of the crosswalk in isolation. And I have misgivings about continuing to use my `OAISolr::Set` name since it may sow confusion even though it's namespaced.

2023-03-28 20:12 UTC, aelkiss commented on docker-compose.yml
> +  test-persist:
Verified `docker-compose run test bash` works as expected; removing this

2023-03-28 20:16 UTC, aelkiss commented on lib/oai_solr/dublin_core.rb
> +      dc["format"] ||= CROSSWALK.format(marc)
Oh, it's doing `||=` - so I think we can leave it, and the same for publisher.

2023-03-28 20:59 UTC, aelkiss commented on lib/oai_solr/basic_marc_single_extractor.rb
> +      define_singleton_method(:matches_tag?, tag_matcher(@tags))
@moseshll  and I made some attempt to refactor this, but ended up in a situation where tests started failing and we couldn't get a `binding.pry` to fire to figure out why. Probably not worth spending a great deal of time on.

2023-03-29 01:47 UTC, billdueber commented on lib/oai_solr/basic_marc_extractor.rb
> +  class BasicMARCExtractor
The equivalent code in traject doesn't allow for ranges of fields, which isn't the worst thing ever, or for using regexp for tags/subfields/indicators.  It might be smart to use the traject code anyway (although pulling in all of traject just for this feels weird), and it might even be smarter to save all this over-engineered nonsense for a rainy day and just write non-DRY methods, one for each DC field. I'm open to either or neither.

2023-03-29 01:53 UTC, billdueber commented
Having read your comments and re-read my code, I'm sorely tempted to just write a couple utility functions as needed and just have a nice, simple method for each DC field. It'll be less efficient and not have the nice all-the-configuration-in-a-hash thing I've got going now, but it'll be less clever by half and easier to understand and test. @aelkiss , @moseshll have an opinion? I'll save the extractor code regardless, 'cause it'll likely come in handy some day.

2023-04-03 13:54 UTC, moseshll approved these changes

2023-04-10 18:37 UTC, merged