Handle deleted items
hathitrust/oai_solr pull request #9
Opened 2022-09-29 15:14 UTC by aelkiss

- clean up rspec setup - enable spec_helper, load application by default
  - so we can run individual specs

- remove extranous pry requires

2022-09-29 20:17 UTC, aelkiss commented
@billdueber  These all work now whereas before (and with staging.oai.kubernetes.hathitrust.org which has what's on main) they don't.

https://testing.oai.kubernetes.hathitrust.org/oai?verb=ListRecords&metadata_prefix=oai_dc&set=hathitrust:pd
https://testing.oai.kubernetes.hathitrust.org/oai?verb=ListRecords&metadata_prefix=oai_dc&set=hathitrust:pdus
https://testing.oai.kubernetes.hathitrust.org/oai?verb=ListRecords&metadata_prefix=oai_dc

https://testing.oai.kubernetes.hathitrust.org/oai?verb=ListRecords&metadata_prefix=marc21&set=hathitrust:pd
https://testing.oai.kubernetes.hathitrust.org/oai?verb=ListRecords&metadata_prefix=marc21&set=hathitrust:pdus
https://testing.oai.kubernetes.hathitrust.org/oai?verb=ListRecords&metadata_prefix=marc21

The contents of the subsets isn't correct in terms of what rights it's looking for in individual items, but that's for another day.

2022-10-04 21:10 UTC, moseshll approved these changes
Looks good here. Including cleanup of a couple "little messes" (e.g., `require "pry"`) I prolly made.

2022-10-11 14:08 UTC, billdueber requested changes

2022-10-11 14:08 UTC, billdueber commented on lib/oai_solr/dublin_core.rb
> +    def dublin_core_hash(record)
A couple thoughts here:
 * Is this method actually returning the completed hash? I think it'll just return the list of ISBNs (or `nil` if there aren't any)
  * Catalog documents aren't guaranteed to have most of these  fields -- might want to guard against adding empty arrays  by returning `dc.reject{|_k, v| [nil, []].include? v}`

2022-11-04 15:34 UTC, aelkiss commented
Should subclass `OAI::Record` to include `OAI::DeletedRecord` and have them know what to do in terms of output to MARC and DC.

2022-11-07 18:42 UTC, aelkiss commented on lib/oai_solr/dublin_core.rb
> +    def dublin_core_hash(record)
@billdueber Added tests to address both these issues and added the suggested `.reject`

2022-11-07 18:49 UTC, aelkiss commented
Test passed for me locally I think because I didn't have the latest ghcr.io/hathitrust/catalog-solr-sample image locally

2022-11-07 18:58 UTC, aelkiss commented
Tests failed again in GHA. Maddening. @billdueber @moseshll Do they pass for you locally?

2022-11-07 20:21 UTC, moseshll commented
@aelkiss I can't get this branch to fail locally.

2022-11-07 20:25 UTC, aelkiss commented
Argh. What is going on??

2022-11-10 21:18 UTC, aelkiss commented
Looking at the failures with fresh eyes I suspect that the issue has to do with validating against `http://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd` and in particular maybe what's going on is that it's pulling it down over and over in the tests & getting throttled or something. I will see what I can do.

2022-11-10 21:36 UTC, aelkiss commented
@moseshll  See the latest commit. Does using `validateCache` on x86 and falling back to `StdInParse` on arm seem like a problem? Building multiarch feed seems like more rigmarole than I want just to get an ARM version of validateCache. Suppose we could just build an arm binary and bake it in to the repo? Ugh. Too much yak shaving for me...

2022-11-11 18:12 UTC, aelkiss commented
Thoughts about how to address the ARM issue:

- Only run tests with validation on x86?
- Use jruby for tests for multi-schema validation? This seems better to me...

2022-11-11 18:17 UTC, aelkiss commented
Created DEV-509 as a workaround for this.

2022-11-11 18:17 UTC, merged